import type { Metadata } from 'next';
import './global.css';
import { IRANSansXFaNum } from '@/configuration/localFonts';
import { ReactNode } from 'react';
// import { ThemeProvider } from '@/providers';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body
        className={`${IRANSansXFaNum.className} ${IRANSansXFaNum.variable}`}
      >
        {/* <ThemeProvider> */}
        <main>{children}</main>
        {/* </ThemeProvider> */}
      </body>
    </html>
  );
}
